branches:
  only:
  - master
  - xmppmaster
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y python-sqlalchemy python-mysqldb python-twisted-web python-ldap
  python-gobject xsltproc docbook-xsl
install: sh -c ' cd core && sh autogen.sh && ./configure && make && sudo make install
  &&  sh autogen.sh && ./configure && make && sudo make install '
script:
- echo "DONE"
notifications:
  email:
    recipients:
    - yvan.manon@siveo.net
    on_success: change
    on_failure: always
  irc:
    channels:
      - "irc.freenode.net#pulse-fr"
      - "irc.freenode.net#pulse-en"
    on_success: always #|never|change] # default: always
    on_failure: always #|never|change] # default: always
